language: node_js
node_js: node
cache:
  directories:
    - node_modules
env:
  - CI=true
deploy:
  b18a5867-e44e-4007-818a-b54936842203:
    secure: uVZ21LGLloSk+JXP3skuJZo8hOYWQvRcsTmGh5DCvSo07tZ8Gh3xaMTFc63vNKHfcIdZM6Ehv4cCoboflgWsyDdqdyAn11tvHsAfFstsFEi+QGETyZevjYvBvjNJJ9ctU6UprdxBfWSZAWxyq+yQhtPh7xxmdXwsTAOz1zftnYbxaLqWWiSGv4z08Ple5yEG3FLe0M6+tqMo4IE7jSVSyJU9J47UL/ow8c4dNuGbZ0EuONfd6r6GgaSv31jOzssEmjSqRUMPC0Ui3pSm0XoYl8FPVHK3ovGHYJ9lmee180xISbeh90odsqgnTeUEpyb76lM4a+YLmqSeW1RnyZ6KZHAZvK6yCKGZo+xkm2BOXw8AkjPbMq2+ImiTpJBruhmjROex9Js/t9WvIrUVFBOL6U62etEcu6qNZKzb5rPj2xVVF069nOmEj2i4Z9cqbLUGYl1bRUdmAOHTVgZqIs+cMr574U9a892BmPY2jYmC8zZONtbRqiea3D+lxWkH8PAiU5H7dAEhvYA/2qQl+Hew8yGL5av66tSw8fDFrPmVIdPjEy8tJBWaas7HakSpZoA853P77BSqbu38Bl1WrIgFhi2ssDr6ed3GEzlgeN+DPpv2vgNfN9HcFxvi/wn4mut+0TAW8XXQNFUtYXZnmIQz6q7sO4Wz6YRkcqjOg0gHNC8=
